apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  #namespace: tekton-pipelines
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v1/
type: kubernetes.io/basic-auth
stringData:
    username: ${DOCKER_REPO}
    password: ${DOCKER_PASS}
