apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  #namespace: tekton-pipelines
  annotations:
    tekton.dev/git-0: http://github.com
type: kubernetes.io/basic-auth
stringData:
  username: username
  password: "XXXXXX"
