apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-resource
spec:
  type: git
  params:
  - name: url
    value: https://github.com/hbstarjason2021/pipeline-craft
  - name: revision
    value: master
