apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-maven-test
  #namespace: tekton-pipelines
spec:
  resources:
    inputs:
      - name: git-resource
        type: git
  steps:
  - name: maven-test
    image: maven:3.5.2-jdk-8-alpine
    workingDir: /workspace/pipeline-craft/src
    command:
      - mvn
    args:
      - test
    volumeMounts:
      - name:  m2
        mountPath:  /root/.m2
  volumes:
   - name: m2
     hostPath:
      path: /root/.m2
