apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-trivy-image
  #namespace: tekton-pipelines
spec:
  taskRef:
    name: task-trivy-image
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: git-resource
