apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: taskrun-maven-test
spec:
  taskRef:
    name: task-maven-test
  resources:
    inputs:
    - name: repo
      resourceRef:
        name: git-resource
