apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: task-build-and-push
  #namespace: tekton-pipelines
spec:
  resources:
    inputs:
      - name: repo
        type: git
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor
    #workingDir: /workspace/repo
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker
    command:
      - /kaniko/executor
      - --dockerfile=./Dockerfile
      - --destination=hbstarjason/pipeline-craft:tekton
